schema: ./.nest/types/generated/schema.gql
extensions:
  endpoints:
    Local GraphQL Endpoint:
      url: http://localhost:3001/graphql
      headers:
        user-agent: JS GraphQL
      introspect: false
